name: dcaf
description: An implementation of the ACE-OAuth framework, intended for OAuth clients. Its main feature is CBOR-(de-)serializable data models.
version: 0.1.0-pre
repository: https://github.com/namib-project/dart_dcaf

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  cbor: ^5.0.1
  collection: ^1.16.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  hex: ^0.2.0
